[info]
charname = "Thoradin Fireforge"
classlevel = "Paladin 2"
background = "Acolyte"
playername = "Player McPlayerface"
race = "Half-elf"
alignment = "Lawful Good"
experiencepoints = 3240
Strengthscore = 10
Strengthmod = "+0"
Dexterityscore = 10
Dexteritymod = "+0"
Constitutionscore = 10
Constitutionmod = "+0"
Wisdomscore = 10
Wisdommod = "+0"
Intelligencescore = 10
Intelligencemod = "+0"
Charismascore = 10
Charismamod = "+0"
inspiration = false
proficiencybonus = "+2"
Strength-save = "+0"
Strength-save-prof = false
Dexterity-save = "+0"
Dexterity-save-prof = false
Constitution-save = "+0"
Constitution-save-prof = false
Wisdom-save = "+0"
Wisdom-save-prof = false
Intelligence-save = "+0"
Intelligence-save-prof = false
Charisma-save = "+0"
Charisma-save-prof = false
Acrobatics = "+0"
Acrobatics-prof = false
Animal Handling = "+0"
Animal Handling-prof = false
Arcana = "+0"
Arcana-prof = false
Athletics = "+0"
Athletics-prof = false
Deception = "+0"
Deception-prof = false
History = "+0"
History-prof = false
Insight = "+0"
Insight-prof = false
Intimidation = "+0"
Intimidation-prof = false
Investigation = "+0"
Investigation-prof = false
Medicine = "+0"
Medicine-prof = false
Nature = "+0"
Nature-prof = false
Perception = "+0"
Perception-prof = false
Performance = "+0"
Performance-prof = false
Persuasion = "+0"
Persuasion-prof = false
Religion = "+0"
Religion-prof = false
"Sleight of Hand" = "+0"
"Sleight of Hand-prof" = false
Stealth = "+0"
Stealth-prof = false
Survival = "+0"
Survival-prof = false
passiveperception = 10
otherprofs = ""
ac = 10
initiative = "+0"
speed = 30
maxhp = 10
currenthp = ""
temphp = ""
totalhd = "2d10"
remaininghd = ""
deathsuccess1 = false
deathsuccess2 = false
deathsuccess3 = false
deathfail1 = false
deathfail2 = false
deathfail3 = false
atkname1 = ""
atkbonus1 = ""
atkdamage1 = ""
atkname2 = ""
atkbonus2 = ""
atkdamage2 = ""
atkname3 = ""
atkbonus3 = ""
atkdamage3 = ""
cp = ""
sp = ""
ep = ""
gp = ""
pp = ""
personality = ""
ideals = ""
bonds = ""
flaws = ""
features = ""
