[package]
name = "open-character-sheet"
version = "0.1.0"
edition = "2018"

[dependencies]
tauri = { version = "1.0", features = ["api-all"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.5"
wasm-bindgen = "0.2"
yew = { version = "0.18", features = ["csr"] }
yew-router = "0.18"

[dev-dependencies]
wasm-bindgen-test = "0.3"